# Sink Configuration File

# Output settings
output: output.md  # Output file path

# File filtering
filter-patterns:
  - "*.go"
  - "*.py"
  - "*.js"
exclude-patterns:
  - "*_test.go"
  - "*.test.js"
case-sensitive: false

# Processing options
no-codeblock: false
line-numbers: true
strip-comments: false

# Token settings
show-tokens: true
token-encoding: cl100k_base

# Price estimation
show-price: false
provider: openai
model: gpt-3.5-turbo
output-tokens: 1000

# Syntax highlighting mappings
syntax-map:
  ".jsx": "javascript"
  ".tsx": "typescript"
  ".mjs": "javascript"
  ".cjs": "javascript"

# Template settings
template-path: ""  # Path to custom template file